version: "3.8"

services:
  user-app:
    build: .
    container_name: ict05-user-app
    environment:
      SPRING_PROFILES_ACTIVE: "purchase"
    expose:
      - "8082"

  user-nginx:
    image: nginx:1.27
    container_name: ict05-user-nginx
    ports:
      - "8086:80"    # 브라우저에서 EC2_IP:8086 로 접속
    volumes:
      - ./nginx.user.conf:/etc/nginx/nginx.conf:ro
      - ./front-end/build:/usr/share/nginx/html:ro
    depends_on:
      - user-app
