events {}

http {
    server {
        listen 80;
        server_name _;

        # /user 포함 전체를 스프링 부트로 프록시
        location / {
            proxy_pass http://user-app:8082;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # 리다이렉트 꼬임 방지
            proxy_redirect off;
        }
    }
}
